// <auto-generated />
using LoLApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoLApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207125413_LoLAppDb7")]
    partial class LoLAppDb7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoLApi.Db.LoLAccount", b =>
                {
                    b.Property<string>("Puuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagLine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Puuid");

                    b.ToTable("LoLAccounts");
                });

            modelBuilder.Entity("LoLApi.Db.LoLMatch", b =>
                {
                    b.Property<string>("Puuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatchIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Puuid");

                    b.ToTable("LoLMatch");
                });

            modelBuilder.Entity("LoLApi.Db.RankedInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RankedInfo");
                });

            modelBuilder.Entity("LoLApi.Db.SummonerAccount", b =>
                {
                    b.Property<string>("Puuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RevisionDate")
                        .HasColumnType("bigint");

                    b.Property<int>("SummonerLevel")
                        .HasColumnType("int");

                    b.HasKey("Puuid");

                    b.ToTable("SummonerAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
